package dev.daisybase.orm;

import dev.daisybase.jdbc.DaisyBaseDataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.math.BigDecimal;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DaisyBaseOrmIntegrationTest {
    @TempDir
    Path tempDir;

    @Test
    void entityManagerSupportsCrudAndGeneratedIdentity() throws Exception {
        DaisyBaseDataSource dataSource = dataSource(tempDir.resolve("orm-crud"));
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE customers (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 1) PRIMARY KEY,
                        name TEXT NOT NULL,
                        credit_limit DECIMAL(12, 2) NOT NULL,
                        active BOOLEAN NOT NULL,
                        created_on DATE NOT NULL
                    );
                    """);
        }

        DaisyBaseEntityManager entityManager = new DaisyBaseOrmSessionFactory(dataSource).createEntityManager();
        CustomerEntity customer = new CustomerEntity();
        customer.name = "Acme Rail";
        customer.creditLimit = new BigDecimal("1200.50");
        customer.active = true;
        customer.createdOn = LocalDate.parse("2026-04-19");

        entityManager.insert(customer);
        assertNotNull(customer.id);
        assertTrue(customer.id >= 10L);

        Optional<CustomerEntity> loaded = entityManager.findById(CustomerEntity.class, customer.id);
        assertTrue(loaded.isPresent());
        assertEquals("Acme Rail", loaded.orElseThrow().name);

        customer.name = "Acme Rail East";
        entityManager.update(customer);
        assertEquals("Acme Rail East", entityManager.findById(CustomerEntity.class, customer.id).orElseThrow().name);

        List<CustomerEntity> queryResults = entityManager.query(CustomerEntity.class)
                .whereEquals("active", true)
                .orderBy("name", true)
                .list();
        assertEquals(1, queryResults.size());

        assertTrue(entityManager.delete(customer));
        assertFalse(entityManager.findById(CustomerEntity.class, customer.id).isPresent());
    }

    @Test
    void introspectorAndGeneratorProduceExpectedMappings() throws Exception {
        DaisyBaseDataSource dataSource = dataSource(tempDir.resolve("orm-introspect"));
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE invoices (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        invoice_code TEXT NOT NULL,
                        total_amount DECIMAL(12, 2) NOT NULL,
                        issued_on DATE NOT NULL
                    );
                    """);
        }

        DaisyBaseOrmIntrospector.SchemaModel model = DaisyBaseOrmIntrospector.inspect(dataSource, "public", "invoices");
        assertEquals(1, model.tables().size());
        assertEquals("InvoiceCode", DaisyBaseEntityMetadata.toClassCase("invoice_code"));
        assertEquals("Long", model.tables().getFirst().idColumn().javaTypeName());

        DaisyBaseOrmCodeGenerator.GenerationBundle bundle = DaisyBaseOrmCodeGenerator.generate(model, "dev.daisybase.generated");
        String entitySource = bundle.sources().get("InvoicesEntity.java");
        assertTrue(entitySource.contains("@Table(schema = \"public\", name = \"invoices\")"));
        assertTrue(entitySource.contains("private BigDecimal totalAmount;"));
        assertTrue(bundle.sources().get("InvoicesRepository.java").contains("extends DaisyBaseRepository<InvoicesEntity, Long>"));
    }

    private static DaisyBaseDataSource dataSource(Path home) {
        DaisyBaseDataSource dataSource = new DaisyBaseDataSource();
        dataSource.setUrl("jdbc:daisybase:embedded:" + home.toAbsolutePath());
        return dataSource;
    }

    @Entity
    @Table(name = "customers")
    public static final class CustomerEntity {
        @Id
        @GeneratedValue
        Long id;

        @Column(nullable = false)
        String name;

        @Column(name = "credit_limit", nullable = false)
        BigDecimal creditLimit;

        @Column(nullable = false)
        Boolean active;

        @Column(name = "created_on", nullable = false)
        LocalDate createdOn;

        public CustomerEntity() {
        }
    }
}
