package dev.daisybase.orm;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.daisybase.jdbc.DaisyBaseDataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DaisyBaseOrmCliTest {
    @TempDir
    Path tempDir;

    @Test
    void cliEmitsSchemaAndGenerationJson() throws Exception {
        Path home = tempDir.resolve("orm-cli");
        DaisyBaseDataSource dataSource = new DaisyBaseDataSource();
        dataSource.setUrl("jdbc:daisybase:embedded:" + home.toAbsolutePath());
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE demo_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_code TEXT NOT NULL);");
        }

        String schemaJson = runCli("--mode", "schema-json", "--url", dataSource.getUrl(), "--schema-pattern", "public", "--table-pattern", "demo_orders");
        JsonNode schemaNode = new ObjectMapper().readTree(schemaJson);
        assertEquals(1, schemaNode.get("tables").size());
        assertEquals("demo_orders", schemaNode.get("tables").get(0).get("tableName").asText());

        String generationJson = runCli("--mode", "generate-json", "--url", dataSource.getUrl(), "--schema-pattern", "public", "--table-pattern", "demo_orders", "--package", "dev.daisybase.generated");
        JsonNode bundleNode = new ObjectMapper().readTree(generationJson);
        assertTrue(bundleNode.get("sources").has("DemoOrdersEntity.java"));
        assertTrue(bundleNode.get("sources").get("DemoOrdersEntity.java").asText().contains("class DemoOrdersEntity"));
    }

    private static String runCli(String... args) throws Exception {
        PrintStream originalOut = System.out;
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try (PrintStream capture = new PrintStream(buffer, true, StandardCharsets.UTF_8)) {
            System.setOut(capture);
            DaisyBaseOrmCli.main(args);
        } finally {
            System.setOut(originalOut);
        }
        return buffer.toString(StandardCharsets.UTF_8);
    }
}
