package dev.daisybase.demo;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

final class SchemaBootstrapper {
    void initialize(DataSource dataSource) {
        try (Connection connection = dataSource.getConnection()) {
            if (tableExists(connection.getMetaData(), "employees")) {
                return;
            }
            connection.setAutoCommit(false);
            try {
                createSchema(connection);
                seedData(connection);
                connection.commit();
            } catch (SQLException exception) {
                connection.rollback();
                throw exception;
            } finally {
                connection.setAutoCommit(true);
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Failed to initialize demo schema", exception);
        }
    }

    private boolean tableExists(DatabaseMetaData metaData, String tableName) throws SQLException {
        try (ResultSet tables = metaData.getTables(null, "public", tableName, new String[]{"TABLE"})) {
            return tables.next();
        }
    }

    private void createSchema(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE employees (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
                    full_name TEXT NOT NULL,
                    title TEXT NOT NULL,
                    status TEXT NOT NULL,
                    capacity INT NOT NULL,
                    daily_billable DECIMAL(12, 2) NOT NULL
                );
                """);
        execute(connection, """
                CREATE TABLE customers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000 INCREMENT BY 1) PRIMARY KEY,
                    name TEXT NOT NULL,
                    segment TEXT NOT NULL,
                    health TEXT NOT NULL,
                    account_owner_id BIGINT NOT NULL
                );
                """);
        execute(connection, """
                CREATE TABLE products (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3000 INCREMENT BY 1) PRIMARY KEY,
                    sku TEXT NOT NULL,
                    name TEXT NOT NULL,
                    unit_price DECIMAL(12, 2) NOT NULL,
                    stock_qty INT NOT NULL,
                    reorder_point INT NOT NULL
                );
                """);
        execute(connection, """
                CREATE TABLE sales_orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4000 INCREMENT BY 1) PRIMARY KEY,
                    customer_id BIGINT NOT NULL,
                    status TEXT NOT NULL,
                    opened_on DATE NOT NULL,
                    due_on DATE NOT NULL,
                    total_amount DECIMAL(12, 2) NOT NULL,
                    notes TEXT
                );
                """);
        execute(connection, """
                CREATE TABLE sales_order_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5000 INCREMENT BY 1) PRIMARY KEY,
                    order_id BIGINT NOT NULL,
                    line_no INT NOT NULL,
                    product_id BIGINT NOT NULL,
                    quantity INT NOT NULL,
                    unit_price DECIMAL(12, 2) NOT NULL,
                    line_total DECIMAL(12, 2) NOT NULL
                );
                """);
        execute(connection, """
                CREATE TABLE invoices (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6000 INCREMENT BY 1) PRIMARY KEY,
                    order_id BIGINT NOT NULL,
                    invoice_code TEXT NOT NULL,
                    issued_on DATE NOT NULL,
                    amount DECIMAL(12, 2) NOT NULL,
                    state TEXT NOT NULL
                );
                """);
        execute(connection, "CREATE UNIQUE INDEX products_sku_idx ON products (sku);");
        execute(connection, "CREATE UNIQUE INDEX invoices_code_idx ON invoices (invoice_code);");
        execute(connection, "CREATE INDEX customers_owner_idx ON customers (account_owner_id);");
        execute(connection, "CREATE INDEX sales_orders_customer_idx ON sales_orders (customer_id);");
        execute(connection, "CREATE INDEX sales_orders_status_idx ON sales_orders (status);");
        execute(connection, "CREATE INDEX sales_order_items_order_idx ON sales_order_items (order_id);");
        execute(connection, "CREATE INDEX sales_order_items_product_idx ON sales_order_items (product_id);");
        execute(connection, """
                CREATE FUNCTION public.billable_total(p_amount DECIMAL(12, 2)) RETURN DECIMAL(12, 2) IS
                BEGIN
                  RETURN p_amount + 12.50;
                END;
                """);
        execute(connection, """
                CREATE PROCEDURE public.fulfill_order(p_order_id BIGINT, p_status OUT TEXT) AS
                BEGIN
                  UPDATE sales_orders SET status = 'FULFILLED' WHERE id = p_order_id;
                  p_status := 'FULFILLED';
                END;
                """);
    }

    private void seedData(Connection connection) throws SQLException {
        execute(connection, """
                INSERT INTO employees (id, full_name, title, status, capacity, daily_billable) VALUES
                (101, 'Mara Voss', 'VP Operations', 'FOCUSED', 92, 1800.00),
                (102, 'Theo Raman', 'Account Director', 'TRAVEL', 78, 1450.00),
                (103, 'Inez Solari', 'Supply Lead', 'ON_DECK', 88, 1325.00),
                (104, 'Jon Park', 'Field Engineer', 'DISPATCHED', 70, 1180.00);
                """);
        execute(connection, """
                INSERT INTO customers (id, name, segment, health, account_owner_id) VALUES
                (201, 'Acme Rail', 'Enterprise', 'STABLE', 102),
                (202, 'Horizon Foods', 'Growth', 'AT_RISK', 102),
                (203, 'Northwind Clinics', 'Enterprise', 'EXPANDING', 101),
                (204, 'Helio Ports', 'Strategic', 'STABLE', 101);
                """);
        execute(connection, """
                INSERT INTO products (id, sku, name, unit_price, stock_qty, reorder_point) VALUES
                (301, 'OPS-DESK', 'Operations Desk Bundle', 450.00, 11, 5),
                (302, 'FIELD-KIT', 'Field Readiness Kit', 198.00, 3, 6),
                (303, 'SUPPORT-HR', 'Support Hours Pack', 129.00, 28, 10),
                (304, 'SECURE-GW', 'Secure Gateway Appliance', 648.00, 1, 3);
                """);
        execute(connection, """
                INSERT INTO sales_orders (id, customer_id, status, opened_on, due_on, total_amount, notes) VALUES
                (401, 201, 'OPEN', DATE '2026-04-14', DATE '2026-04-22', 1098.00, 'Expand rail yard monitoring'),
                (402, 202, 'FULFILLED', DATE '2026-04-10', DATE '2026-04-15', 450.00, 'Pilot operations cockpit'),
                (403, 203, 'OPEN', DATE '2026-04-16', DATE '2026-04-24', 198.00, 'Mobile readiness refresh');
                """);
        execute(connection, """
                INSERT INTO sales_order_items (id, order_id, line_no, product_id, quantity, unit_price, line_total) VALUES
                (501, 401, 1, 301, 1, 450.00, 450.00),
                (502, 401, 2, 304, 1, 648.00, 648.00),
                (503, 402, 1, 301, 1, 450.00, 450.00),
                (504, 403, 1, 302, 1, 198.00, 198.00);
                """);
        execute(connection, """
                INSERT INTO invoices (id, order_id, invoice_code, issued_on, amount, state) VALUES
                (601, 402, 'INV-402-20260415', DATE '2026-04-15', 462.50, 'POSTED');
                """);
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
