package dev.daisybase.jdbc;

import dev.daisybase.common.Common;
import dev.daisybase.engine.EngineApi;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.NClob;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLXML;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.sql.RowId;
import java.util.ArrayList;
import java.util.List;

class DaisyBaseStatement implements Statement {
    protected final DaisyBaseConnection connection;
    private final int resultSetType;
    private final int resultSetConcurrency;
    private boolean closed;
    private long maxRows;
    private int fetchSize;
    private SQLWarning warning;
    private List<StatementOutcome> outcomes = List.of();
    private int outcomeIndex = -1;
    private final List<String> batchSql = new ArrayList<>();
    private int openResultSets;
    private boolean closeOnCompletion;
    private boolean suppressAutoClose;
    private boolean executed;
    private Common.TupleBatch generatedKeysBatch = Common.TupleBatch.empty();
    private volatile long currentExecutionId = -1L;
    private int queryTimeoutSeconds;

    DaisyBaseStatement(DaisyBaseConnection connection, int resultSetType, int resultSetConcurrency) {
        this.connection = connection;
        this.resultSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        execute(sql);
        ResultSet resultSet = getResultSet();
        if (resultSet == null) {
            throw new SQLException("SQL did not produce a result set");
        }
        return resultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        long updateCount = executeLargeUpdate(sql);
        if (updateCount > Integer.MAX_VALUE) {
            throw new SQLException("Update count exceeds Integer.MAX_VALUE");
        }
        return (int) updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        execute(sql);
        ResultSet resultSet = getResultSet();
        if (resultSet != null) {
            throw new SQLException("SQL produced a result set, not an update count");
        }
        return Math.max(getLargeUpdateCount(), 0L);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS && autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException("Invalid autoGeneratedKeys value: " + autoGeneratedKeys);
        }
        return runSql(sql, autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return runSql(sql, columnIndexes != null && columnIndexes.length > 0);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return runSql(sql, columnNames != null && columnNames.length > 0);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS && autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException("Invalid autoGeneratedKeys value: " + autoGeneratedKeys);
        }
        long updateCount = executeLargeUpdate(sql, autoGeneratedKeys);
        if (updateCount > Integer.MAX_VALUE) {
            throw new SQLException("Update count exceeds Integer.MAX_VALUE");
        }
        return (int) updateCount;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        long updateCount = executeLargeUpdate(sql, columnIndexes);
        if (updateCount > Integer.MAX_VALUE) {
            throw new SQLException("Update count exceeds Integer.MAX_VALUE");
        }
        return (int) updateCount;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        long updateCount = executeLargeUpdate(sql, columnNames);
        if (updateCount > Integer.MAX_VALUE) {
            throw new SQLException("Update count exceeds Integer.MAX_VALUE");
        }
        return (int) updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS && autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException("Invalid autoGeneratedKeys value: " + autoGeneratedKeys);
        }
        runSql(sql, autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS);
        ResultSet resultSet = getResultSet();
        if (resultSet != null) {
            throw new SQLException("SQL produced a result set, not an update count");
        }
        return Math.max(getLargeUpdateCount(), 0L);
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        runSql(sql, columnIndexes != null && columnIndexes.length > 0);
        ResultSet resultSet = getResultSet();
        if (resultSet != null) {
            throw new SQLException("SQL produced a result set, not an update count");
        }
        return Math.max(getLargeUpdateCount(), 0L);
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        runSql(sql, columnNames != null && columnNames.length > 0);
        ResultSet resultSet = getResultSet();
        if (resultSet != null) {
            throw new SQLException("SQL produced a result set, not an update count");
        }
        return Math.max(getLargeUpdateCount(), 0L);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        return runSql(sql, false);
    }

    protected final boolean runSql(String sql) throws SQLException {
        return runSql(sql, false);
    }

    protected final boolean runSql(String sql, boolean requestGeneratedKeys) throws SQLException {
        prepareForExecution();
        currentExecutionId = connection.nextExecutionId();
        try {
            EngineApi.BatchResult batchResult = connection.executeSql(sql, currentExecutionId, timeoutMillis());
            completeExecution(materializeBatchResult(batchResult, requestGeneratedKeys, sql));
            return getResultSet() != null;
        } finally {
            currentExecutionId = -1L;
        }
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        ensureOpen();
        return currentOutcome() == null ? null : currentOutcome().resultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        long count = getLargeUpdateCount();
        if (count > Integer.MAX_VALUE) {
            return Statement.SUCCESS_NO_INFO;
        }
        return (int) count;
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        ensureOpen();
        StatementOutcome outcome = currentOutcome();
        return outcome == null || outcome.resultSet() != null ? -1 : outcome.updateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(Statement.CLOSE_CURRENT_RESULT);
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        ensureOpen();
        if (current != Statement.CLOSE_CURRENT_RESULT && current != Statement.CLOSE_ALL_RESULTS && current != Statement.KEEP_CURRENT_RESULT) {
            throw new SQLException("Invalid current result handling mode: " + current);
        }
        if (outcomes.isEmpty()) {
            return false;
        }
        if (current == Statement.CLOSE_CURRENT_RESULT) {
            closeResultSet(currentOutcome());
        } else if (current == Statement.CLOSE_ALL_RESULTS) {
            discardOutcomes();
        }
        outcomeIndex++;
        if (outcomeIndex >= outcomes.size()) {
            outcomeIndex = outcomes.size();
            maybeAutoCloseWhenComplete();
            return false;
        }
        return getResultSet() != null;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        ensureOpen();
        batchSql.add(sql);
    }

    @Override
    public void clearBatch() {
        batchSql.clear();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        long[] large = executeLargeBatch();
        int[] counts = new int[large.length];
        for (int index = 0; index < large.length; index++) {
            counts[index] = large[index] > Integer.MAX_VALUE ? Statement.SUCCESS_NO_INFO : (int) large[index];
        }
        return counts;
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        ensureOpen();
        long[] counts = new long[batchSql.size()];
        for (int index = 0; index < batchSql.size(); index++) {
            runSql(batchSql.get(index));
            if (getResultSet() != null) {
                throw new SQLException("Batch entry produced a result set at index " + index);
            }
            counts[index] = getLargeUpdateCount();
        }
        clearBatch();
        return counts;
    }

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        closed = true;
        discardOutcomes();
        connection.unregister(this);
    }

    @Override
    public int getMaxFieldSize() {
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        if (max != 0) {
            throw new SQLFeatureNotSupportedException("Max field size is not supported");
        }
    }

    @Override
    public int getMaxRows() {
        return maxRows > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) maxRows;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        setLargeMaxRows(max);
    }

    @Override
    public long getLargeMaxRows() {
        return maxRows;
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        if (max < 0) {
            throw new SQLException("maxRows must be non-negative");
        }
        this.maxRows = max;
    }

    @Override
    public void setEscapeProcessing(boolean enable) {
    }

    @Override
    public int getQueryTimeout() {
        return queryTimeoutSeconds;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        if (seconds < 0) {
            throw new SQLException("Query timeout must be non-negative");
        }
        queryTimeoutSeconds = seconds;
    }

    @Override
    public void cancel() throws SQLException {
        long executionId = currentExecutionId;
        if (executionId < 0) {
            return;
        }
        connection.cancelExecution(executionId);
    }

    @Override
    public SQLWarning getWarnings() {
        return warning;
    }

    @Override
    public void clearWarnings() {
        warning = null;
    }

    @Override
    public void setCursorName(String name) {
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public int getResultSetType() {
        return resultSetType;
    }

    @Override
    public int getResultSetConcurrency() {
        return resultSetConcurrency;
    }

    @Override
    public int getResultSetHoldability() {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public int getFetchDirection() {
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (direction != ResultSet.FETCH_FORWARD) {
            throw new SQLFeatureNotSupportedException("Only FETCH_FORWARD is supported");
        }
    }

    @Override
    public int getFetchSize() {
        return fetchSize;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        if (rows < 0) {
            throw new SQLException("fetchSize must be non-negative");
        }
        fetchSize = rows;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        ensureOpen();
        if (generatedKeysBatch.columns().isEmpty()) {
            return DaisyBaseResultSets.empty("GENERATED_KEY");
        }
        return DaisyBaseResultSets.fromTupleBatch(generatedKeysBatch, 0);
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public void setPoolable(boolean poolable) {
    }

    @Override
    public boolean isPoolable() {
        return false;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        ensureOpen();
        closeOnCompletion = true;
        maybeAutoCloseWhenComplete();
    }

    @Override
    public boolean isCloseOnCompletion() {
        return closeOnCompletion;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    protected final List<StatementOutcome> materialize(EngineApi.BatchResult batchResult,
                                                       DaisyBaseUpdatableQueries.Descriptor updatableDescriptor) throws SQLException {
        List<StatementOutcome> resolved = new ArrayList<>();
        for (int index = 0; index < batchResult.statements().size(); index++) {
            EngineApi.StatementResult statementResult = batchResult.statements().get(index);
            resolved.add(new StatementOutcome(track(DaisyBaseResultSets.fromStatementResult(statementResult, maxRows, this,
                            index == 0 ? updatableDescriptor : null)),
                    statementResult.updateCount(), statementResult.commandTag()));
        }
        return resolved;
    }

    protected BatchMaterialization materializeBatchResult(EngineApi.BatchResult batchResult,
                                                          boolean requestGeneratedKeys,
                                                          String sql) throws SQLException {
        DaisyBaseUpdatableQueries.Descriptor updatableDescriptor = resultSetConcurrency == ResultSet.CONCUR_UPDATABLE
                ? DaisyBaseUpdatableQueries.describe(sql, firstBatch(batchResult), connection)
                : null;
        return new BatchMaterialization(materialize(batchResult, updatableDescriptor),
                requestGeneratedKeys ? collectGeneratedKeys(batchResult) : Common.TupleBatch.empty());
    }

    protected final void ensureOpen() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed");
        }
    }

    protected final void prepareForExecution() throws SQLException {
        ensureOpen();
        discardOutcomes();
    }

    protected final void completeExecution(BatchMaterialization materialized) throws SQLException {
        outcomes = materialized.outcomes();
        generatedKeysBatch = materialized.generatedKeys();
        outcomeIndex = outcomes.isEmpty() ? -1 : 0;
        executed = true;
        maybeAutoCloseWhenComplete();
    }

    protected final void setCurrentExecutionId(long executionId) {
        currentExecutionId = executionId;
    }

    protected final long timeoutMillis() {
        return queryTimeoutSeconds <= 0 ? 0L : queryTimeoutSeconds * 1000L;
    }

    private StatementOutcome currentOutcome() {
        if (outcomeIndex < 0 || outcomeIndex >= outcomes.size()) {
            return null;
        }
        return outcomes.get(outcomeIndex);
    }

    private ResultSet track(ResultSet resultSet) {
        if (resultSet == null) {
            return null;
        }
        openResultSets++;
        InvocationHandler handler = new InvocationHandler() {
            private boolean resultSetClosed;

            @Override
            public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                return switch (method.getName()) {
                    case "close" -> {
                        if (!resultSetClosed) {
                            resultSetClosed = true;
                            try {
                                resultSet.close();
                            } finally {
                                onResultSetClosed();
                            }
                        }
                        yield null;
                    }
                    case "isClosed" -> resultSetClosed;
                    case "unwrap" -> {
                        Class<?> iface = (Class<?>) args[0];
                        if (iface.isInstance(proxy)) {
                            yield iface.cast(proxy);
                        }
                        if (iface.isInstance(resultSet)) {
                            yield iface.cast(resultSet);
                        }
                        throw new SQLException("Not a wrapper for " + iface.getName());
                    }
                    case "isWrapperFor" -> {
                        Class<?> iface = (Class<?>) args[0];
                        yield iface.isInstance(proxy) || iface.isInstance(resultSet);
                    }
                    case "getClob" -> DaisyBaseJdbcObjects.resultSetClob(resultSet, args[0]);
                    case "getNClob" -> DaisyBaseJdbcObjects.resultSetNClob(resultSet, args[0]);
                    case "getSQLXML" -> DaisyBaseJdbcObjects.resultSetSqlXml(resultSet, args[0]);
                    case "getBlob" -> DaisyBaseJdbcObjects.resultSetBlob(resultSet, args[0]);
                    case "getArray" -> DaisyBaseJdbcObjects.resultSetArray(resultSet, args[0]);
                    case "getRef" -> DaisyBaseJdbcObjects.resultSetRef(resultSet, args[0]);
                    case "getRowId" -> DaisyBaseJdbcObjects.resultSetRowId(resultSet, args[0]);
                    case "getBytes" -> {
                        if (DaisyBaseJdbcObjects.isTextColumn(resultSet, args[0])) {
                            yield DaisyBaseJdbcObjects.resultSetBytes(resultSet, args[0]);
                        }
                        yield invokeResultSet(method, resultSet, args);
                    }
                    case "getCharacterStream" -> {
                        if (DaisyBaseJdbcObjects.isTextColumn(resultSet, args[0])) {
                            yield DaisyBaseJdbcObjects.resultSetCharacterStream(resultSet, args[0]);
                        }
                        yield invokeResultSet(method, resultSet, args);
                    }
                    case "getNCharacterStream" -> {
                        if (DaisyBaseJdbcObjects.isTextColumn(resultSet, args[0])) {
                            yield DaisyBaseJdbcObjects.resultSetCharacterStream(resultSet, args[0]);
                        }
                        yield invokeResultSet(method, resultSet, args);
                    }
                    case "getObject" -> {
                        if (args != null && args.length == 2 && args[1] instanceof Class<?> type
                                && DaisyBaseJdbcObjects.isSpecialObjectType(type)) {
                            if (type == Clob.class) {
                                yield DaisyBaseJdbcObjects.resultSetClob(resultSet, args[0]);
                            }
                            if (type == NClob.class) {
                                yield DaisyBaseJdbcObjects.resultSetNClob(resultSet, args[0]);
                            }
                            if (type == SQLXML.class) {
                                yield DaisyBaseJdbcObjects.resultSetSqlXml(resultSet, args[0]);
                            }
                            if (type == Blob.class) {
                                yield DaisyBaseJdbcObjects.resultSetBlob(resultSet, args[0]);
                            }
                            if (type == Array.class) {
                                yield DaisyBaseJdbcObjects.resultSetArray(resultSet, args[0]);
                            }
                            if (type == java.sql.Struct.class) {
                                yield DaisyBaseJdbcObjects.resultSetStruct(resultSet, args[0]);
                            }
                            if (type == Ref.class) {
                                yield DaisyBaseJdbcObjects.resultSetRef(resultSet, args[0]);
                            }
                            if (type == RowId.class) {
                                yield DaisyBaseJdbcObjects.resultSetRowId(resultSet, args[0]);
                            }
                        }
                        yield invokeResultSet(method, resultSet, args);
                    }
                    case "toString" -> "DaisyBaseResultSet[" + resultSet + "]";
                    case "hashCode" -> System.identityHashCode(proxy);
                    case "equals" -> proxy == args[0];
                    default -> invokeResultSet(method, resultSet, args);
                };
            }
        };
        return (ResultSet) Proxy.newProxyInstance(
                DaisyBaseStatement.class.getClassLoader(),
                new Class[]{ResultSet.class},
                handler);
    }

    private Object invokeResultSet(Method method, ResultSet resultSet, Object[] args) throws Throwable {
        try {
            return method.invoke(resultSet, args);
        } catch (InvocationTargetException invocationTargetException) {
            throw invocationTargetException.getTargetException();
        }
    }

    private void discardOutcomes() throws SQLException {
        suppressAutoClose = true;
        try {
            for (StatementOutcome outcome : outcomes) {
                closeResultSet(outcome);
            }
        } finally {
            outcomes = List.of();
            outcomeIndex = -1;
            generatedKeysBatch = Common.TupleBatch.empty();
            suppressAutoClose = false;
        }
    }

    private Common.TupleBatch collectGeneratedKeys(EngineApi.BatchResult batchResult) {
        List<Common.ResultColumn> columns = List.of();
        List<Common.ResultRow> rows = new ArrayList<>();
        for (EngineApi.StatementResult statement : batchResult.statements()) {
            Common.TupleBatch batch = statement.generatedKeys();
            if (batch == null || batch.columns().isEmpty()) {
                continue;
            }
            if (columns.isEmpty()) {
                columns = batch.columns();
            }
            rows.addAll(batch.rows());
        }
        return columns.isEmpty() ? Common.TupleBatch.empty() : new Common.TupleBatch(columns, rows);
    }

    private Common.TupleBatch firstBatch(EngineApi.BatchResult batchResult) {
        if (batchResult.statements().size() != 1) {
            return Common.TupleBatch.empty();
        }
        return batchResult.statements().getFirst().batch();
    }

    private void closeResultSet(StatementOutcome outcome) throws SQLException {
        if (outcome != null && outcome.resultSet() != null && !outcome.resultSet().isClosed()) {
            outcome.resultSet().close();
        }
    }

    private void onResultSetClosed() throws SQLException {
        if (openResultSets > 0) {
            openResultSets--;
        }
        maybeAutoCloseWhenComplete();
    }

    private void maybeAutoCloseWhenComplete() throws SQLException {
        if (!suppressAutoClose && closeOnCompletion && executed && !closed && openResultSets == 0) {
            close();
        }
    }

    protected record StatementOutcome(ResultSet resultSet, long updateCount, String commandTag) {
    }

    protected record BatchMaterialization(List<StatementOutcome> outcomes, Common.TupleBatch generatedKeys) {
    }
}
