package dev.daisybase.jdbc;

import dev.daisybase.engine.EngineApi;
import dev.daisybase.engine.EmbeddedDatabaseEngine;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LegacyJavaDbCompatibilityTest {
    @TempDir
    Path tempDir;

    @Test
    void legacyDriverAndDataSourceRemainUsable() throws Exception {
        Path home = tempDir.resolve("legacy-db");
        try (EngineApi.DatabaseEngine ignored = EmbeddedDatabaseEngine.open(EngineApi.DatabaseConfig.defaults(home))) {
            // bootstrap the home
        }

        Class.forName("dev.javadb.jdbc.JavaDbDriver");
        try (Connection connection = DriverManager.getConnection("jdbc:javadb:embedded:" + home)) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table customers (id bigint generated by default as identity primary key, name text not null);");
                statement.executeUpdate("insert into customers(name) values ('legacy');");
            }
        }

        dev.javadb.jdbc.JavaDbDataSource dataSource = new dev.javadb.jdbc.JavaDbDataSource();
        dataSource.setUrl("jdbc:javadb:embedded:" + home);
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select name from customers")) {
            assertTrue(resultSet.next());
            assertEquals("legacy", resultSet.getString(1));
        }
    }
}
